# This is a very simple environment.yml for Anaconda without fixed versions.
name: 36c3
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates
  - certifi
  - jupyter
  - openssl
  - pip
  - python=3.7
  - setuptools
  - spacy-model-en_core_web_sm
  - sqlite
  - wheel
  - pip:
    - en-core-web-sm

