name: 36c3
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates
  - certifi
  - openssl
  - spacy-model-en_core_web_sm
  - pip
  - python=3.7
  - setuptools
  - sqlite
  - vc
  - vs2015_runtime
  - wheel
  - wincertstore
  - pip:
    - en-core-web-sm

